name: Sync localization

on:
  push:
    branches:
      - master
    paths:
      - 'i18n/**'

jobs:
  sync-localization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sync to release branches
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          for branch in REL1_35 REL1_39 REL1_40
          do
            git checkout $branch
            git cherry-pick ${{ github.sha }}
            git push
          done
